# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-devops-terraform-aws-static-site"
    dynamodb_table = "terraform-devops-terraform-aws-static-site"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
